# Generated by Django 2.0.3 on 2018-03-31 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
                ('categoryCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryName', models.CharField(max_length=20)),
                ('subcategoryCode', models.CharField(max_length=10)),
                ('category_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPreference.category')),
            ],
        ),
        migrations.CreateModel(
            name='userPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceCode', models.CharField(max_length=10)),
                ('preferenceScore', models.IntegerField(default=None)),
                ('userId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userSubPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpreferenceCode', models.CharField(max_length=10)),
                ('subpreferenceScore', models.IntegerField(default=None)),
                ('userpreference_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPreference.userPreference')),
            ],
        ),
    ]
