# Generated by Django 2.0.3 on 2018-03-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceName', models.CharField(max_length=15)),
                ('preferenceScore', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='userSubPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpreferenceName', models.CharField(max_length=15)),
                ('subpreferenceScore', models.IntegerField(default=None)),
                ('userpreference_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPreference.userPreference')),
            ],
        ),
    ]
