# Generated by Django 2.0.3 on 2018-03-28 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userPreference', '0002_auto_20180327_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubpreference',
            name='subpreferenceName',
        ),
        migrations.AddField(
            model_name='usersubpreference',
            name='subpreferenceCode',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='usersubpreference',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
