# Generated by Django 2.0.3 on 2018-03-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPreference', '0003_auto_20180328_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubpreference',
            name='userId',
        ),
    ]
