# Generated by Django 2.0.3 on 2018-03-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPreference', '0004_remove_usersubpreference_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategoryCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferenceCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usersubpreference',
            name='subpreferenceCode',
            field=models.CharField(max_length=10),
        ),
    ]
