# Generated by Django 2.0.3 on 2018-03-29 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userPreference', '0005_auto_20180328_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userPreference',
            new_name='userPreferences',
        ),
        migrations.RenameModel(
            old_name='userSubPreference',
            new_name='userSubPreferences',
        ),
    ]
